### ISSUE TITLE
Emunand 9.6 Incompatible

### ISSUE THREAD

**Issue by LfxB** [44670/BootNTR#1]
strHidUser: 0032611b
refHidUser: 0030c7ac
hidObj: 00360da8
{'gxFlushDCahce': '0x12ddf4', 'fsOpenFile': '0x16361c', 'mountArchive': '0x12bf88', 'userFsTryOpen': '0x22babc', 'nnInitCardUpd': '0x118cf0', 'regArchive': '0x2280b8', 'fsOpenArchive': '0x21eb9c', 'fsWriteFile': '0x1636f8', 'mountRom': '0x10ee28', 'hidObj': '0x360da8', 'fsReadFile': '0x12c0c0', 'getServiceHandle': '0x235758', 'aptStartApplet': '0x12e92c', 'fsUserHandle': '0x32efac'}
if (t == 0xe1530005 ) {
ntrConfig->HomeMenuVersion = 9.6.0-24U;
ntrConfig->HomeMenuInjectAddr = 0x12ddf4;
ntrConfig->HomeFSReadAddr = 0x12c0c0;
ntrConfig->HomeCardUpdateInitAddr = 0x118cf0;
ntrConfig->HomeFSUHandleAddr = 0x32efac;
ntrConfig->HomeAptStartAppletAddr = 0x12e92c;
}

kversion: 02320100

**Comment by 44670** [comment]
what's your consoles region?

**Comment by b1l1s** [comment]
The output is the same as my JP.

**Comment by LfxB** [comment]
It is USA

**Comment by 44670** [comment]
thanks, please try the latest build.
