### ISSUE TITLE
Themehax

### ISSUE THREAD

**Issue by gudenau** [44670/BootNTR#15]
It would be grrat if NTR could load on boot using ThemeHax.

**Comment by 44670** [comment]
current not possible because you can not return to home menu after launching *hax.

**Comment by 44670** [comment]
Currently not possible because you can not return to home menu after launching *hax.

**Comment by gudenau** [comment]
Why could you not restore the home menu like the hax does when not running otherapp?

**Comment by 44670** [comment]
I think it should be hard to do that.
