### ISSUE TITLE
Boot check? Boot twice? gdbstub?

### ISSUE THREAD

**Issue by Syphurith** [44670/BootNTR#16]
Even i thought i can speak Chinese in this issue i'd better keep using english so someone else could understand this. And i'm lazy so i would ask all questions in one issue.

1.As you may already now, the console would partially loads other modules, after it gets all embeded NCCHs loaded and booted. So it would fail if the system is just open, and for maybe one minute or more, it could be patched safely.
So my suggestion is to check if the modules needed to be patched is fully loaded or not. If you can load process list, and then the memory regions you might be able to test if its rear is loaded.
Or else if you have access to system up time, you can refuse to boot ntr if that is smaller than 1 minute.

2.As you know, using some certain apps after ntr would clear some of its patches. Since it was ever booted before, the patch checks would fail and thus boot failure on its second time before reboot.
If you haven't met this before.. I was using my O3DS SYS9.2-EMU9.8, After booted it in emunand, i used the notification applet, and then the games with cheats don't show the green screen.

3.Gdbstub. I know that the currently ntr and ntrclient are good for some guys to dig some information inside the system, however i don't know if there is any plan on implementation of a gdbstub. A gdbstub can be used to connect to gdb, and thus you can debug something on IDA Pro..
A gdbstub doesn't request much to be implemented. I wrote a issue on ntrclient-DEX repo however nothing pops up. So i don't know if that's rejected or no plan to do so.

And, you seem to be keeping the newest source again. That is easy to figure out only the output/release folder updated, but the source remains 2 months ago. However if open the source would cause ninty to update their code to attack your method, just keep it longer this time.
I had to admit this is a good tool for all of us, even i don't want to participate in your development.
*Where is your WOW typed avatar? When did you change that shinba to this one?*

**Comment by 44670** [comment]
1.the process that ntr needs to patch is already started when you can interact with home menu, it is totally safe to patch them.
2.it happens on old3ds only, because on old3ds system will terminate the home menu process when starting certain applets in order to ensure enough free memory.
3.there are no plans for a gdb stub, however you could make one since the ntrclient is an open-source project.

**Comment by Syphurith** [comment]
@44670 Thanks for reply. I know now and would close this.

**Comment by Syphurith** [comment]
@44670 Oh i've forget one thing. What is needed when you want to load it from ARM9? Since Old3ds doesn't have extra ram, the games like smash would kill HomeMenu and NTR break. However via Reboot triggers the signatures checks are still patched. If they could load the ARM11 payload well from firmlaunch I think that's quite a good way for NTR to load, or even Prepatched modules might work (d0k3 have injection method now and can replace original when sig-checks patched).

**Comment by 44670** [comment]
It is possible without arm9 access, however the solution still have some compatibility issues so it won't be released with ntr 3.1

**Comment by Syphurith** [comment]
@44670 Yes that's good to hear it still have further plans. Thanks.
*There maybe a real C# UI form for ntr debugger one day.that I can't predict.*
