### ISSUE TITLE
Cannot open CHMM

### ISSUE THREAD

**Issue by bryanLow-sq** [44670/BootNTR#21]
Prior to running NTR on rxtools, CHMM could open and change themes with no problem, however upon running NTR and reopening CHMM, a eternal blank screen is observed happening.
Retesting showed that it has something to do with NTR.

**Comment by 44670** [comment]
I see.

**Comment by mariohackandglitch** [comment]
Not only happening with CHMM, also with all lpp3ds homebrew apps.
