### ISSUE TITLE
Cannot Set Breakpoints

### ISSUE THREAD

**Issue by nolberto82** [44670/BootNTR#22]
I have an Old 3DS and used NTR CFW 3.0,3.1 and 3.2 with rxtools but every time I tried to set any breakpoints the debugger returns "invalid bpid". Does this CFW support breakpoints? Thank you in advance.

**Comment by 44670** [comment]
I think code breakpoint is workable for non-dex version of NTR.

**Comment by nolberto82** [comment]
Okay code breakpoint work on NTR 3.2. Are there going to be write/read breakpoints/watchpoints implemented?

**Comment by 44670** [comment]
memory breakpoints are available in dex versions, the latest one is NTR 2.2 DEX

**Comment by nolberto82** [comment]
Does NTR 2.2 DEX work with Old 3DS?

**Comment by 44670** [comment]
it works on new3ds only, however are newer version will be released soon.
