### ISSUE TITLE
10.3.0-28U N3DS unknown firmware

### ISSUE THREAD

**Issue by aroth-khashar** [44670/BootNTR#28]
sysnand: 9.0.0-20U
emunand: 10.3.0-28U (Reinand)
kversion: 02320100

strHidUser: 003250df
refHidUser: 0030b794
hidObj: 0035fda0
{'gxFlushDCahce': '0x12ddc4', 'fsOpenFile': '0x163790', 'mountArchive': '0x12bf58', 'userFsTryOpen': '0x22b98c', 'nnInitCardUpd': '0x118cc0', 'regArchive': '0x227f88', 'fsOpenArchive': '0x21ea80', 'fsWriteFile': '0x16386c', 'mountRom': '0x10ed70', 'hidObj': '0x35fda0', 'fsReadFile': '0x12c090', 'getServiceHandle': '0x235620', 'aptStartApplet': '0x12e8fc', 'fsUserHandle': '0x32dfa4'}
if (t == 0xe8960140 ) {
ntrConfig->HomeMenuVersion = SYSTEM_VERSION(INSERT_YOUR_VERSION_HERE);
ntrConfig->HomeMenuInjectAddr = 0x12ddc4;
ntrConfig->HomeFSReadAddr = 0x12c090;
ntrConfig->HomeCardUpdateInitAddr = 0x118cc0;
ntrConfig->HomeFSUHandleAddr = 0x32dfa4;
ntrConfig->HomeAptStartAppletAddr = 0x12e8fc;
}

**Comment by 44670** [comment]
I think it may have been solved, please try the latest build.

**Comment by aroth-khashar** [comment]
Will do.

**Comment by aroth-khashar** [comment]
Nope, tried the build listed on the front page and even compiled it myself with the same result.

strHidUser: 003250df
refHidUser: 0030b794
hidObj: 0035fda0
{'gxFlushDCahce': '0x12ddc4', 'fsOpenFile': '0x163790', 'mountArchive': '0x12bf58', 'userFsTryOpen': '0x22b98c', 'nnInitCardUpd': '0x118cc0', 'regArchive': '0x227f88', 'fsOpenArchive': '0x21ea80', 'fsWriteFile': '0x16386c', 'mountRom': '0x10ed70', 'hidObj': '0x35fda0', 'fsReadFile': '0x12c090', 'getServiceHandle': '0x235620', 'aptStartApplet': '0x12e8fc', 'fsUserHandle': '0x32dfa4'}
if (t == 0xe8960140 ) {
ntrConfig->HomeMenuVersion = SYSTEM_VERSION(INSERT_YOUR_VERSION_HERE);
ntrConfig->HomeMenuInjectAddr = 0x12ddc4;
ntrConfig->HomeFSReadAddr = 0x12c090;
ntrConfig->HomeCardUpdateInitAddr = 0x118cc0;
ntrConfig->HomeFSUHandleAddr = 0x32dfa4;
ntrConfig->HomeAptStartAppletAddr = 0x12e8fc;
}

**Comment by aroth-khashar** [comment]
4 tests resulted in the following results.

"current firmware not supported"
"NTR CFW loaded successfully" followed by an error when I pressed HOME"
"current firmware not supported"
""NTR CFW loaded successfully" (worked this time)

**Comment by 44670** [comment]
wow, I will investigate on this issue later.

thanks for reporting

**Comment by svanheulen** [comment]
Reinand dump shows "kversion: 02320100"
CakesCFW dump shows "kversion: 02320900"

The new BootNTR.cia works great with CakesCFW, which uses the official, encrypted, unmodified firmware.bin. So maybe it's just an issue with the firmware.bin that Reinand uses?

**Comment by aroth-khashar** [comment]
@svanheulen 

Its a compatibility issue with BootNTR.

Reinand uses the 9.6 NATIVE_FIRM, which has a kernel version of 2.50-1.

Cakes and GW both use the 10.2 NATIVE_FIRM, which has a kernel version of 2.50-9

@44670 

It seems to work just fine on GW now, the only one acting weird is Reinand which, as I said, uses a different version of the native_firm. If you can get it working across the board, great. If not maybe I can use this to convince Reisyukaku to use the newer native_firm.

**Comment by behdad1999** [comment]
Is it possible to make a copy of the bootNTR so that it works on the reinand?

**Comment by aroth-khashar** [comment]
The most recent copy DOES work. Sort of. It if fails, just reboot the system completely and try again. Eventually it will work. Until we get a build with full compatibility that will have to do.

**Comment by behdad1999** [comment]
Thanks man, I re needed that

**Comment by behdad1999** [comment]
Really*
