### ISSUE TITLE
Messed up bottom screen after opening menu

### ISSUE THREAD

**Issue by fakedcake** [44670/BootNTR#3]
This happens after opening the menu in Majoras Mask 3D and Anomal Crossing:New Leaf. I dont know if it also happens in other games or if the bug was present in earlier versions, just noticed it while taking some screenshots.

http://imgur.com/a/Gn152

Thank you!

**Comment by 44670** [comment]
It is a known issue, at this moment it could be solved by setting screenshot hotkeys to do screen-shot without opening NTR Menu.

**Comment by 44670** [comment]
Majoras Mask 3D is compatible with NTR menu now, Animal crossing will be fixed later.
