### ISSUE TITLE
Currently incompatible with 10.4.0-29J

### ISSUE THREAD

**Issue by Flat** [44670/BootNTR#32]
kversion: 02320100
sysNAND: 9.2.0-20J
emuNAND: 10.4.0-29J

>result.txt:
```
strHidUser: 003260df
refHidUser: 0030c794
hidObj: 00360da0
{'gxFlushDCahce': '0x12ded0', 'fsOpenFile': '0x163898', 'mountArchive': '0x12c064', 'userFsTryOpen': '0x22bdbc', 'nnInitCardUpd': '0x118d78', 'regArchive': '0x228338', 'fsOpenArchive': '0x21ee10', 'fsWriteFile': '0x163974', 'mountRom': '0x10ed84', 'hidObj': '0x360da0', 'fsReadFile': '0x12c19c', 'getServiceHandle': '0x2359cc', 'aptStartApplet': '0x12ea08', 'fsUserHandle': '0x32efa4'}
if (t == 0xea00001f ) {
ntrConfig->HomeMenuVersion = SYSTEM_VERSION(INSERT_YOUR_VERSION_HERE);
ntrConfig->HomeMenuInjectAddr = 0x12ded0;
ntrConfig->HomeFSReadAddr = 0x12c19c;
ntrConfig->HomeCardUpdateInitAddr = 0x118d78;
ntrConfig->HomeFSUHandleAddr = 0x32efa4;
ntrConfig->HomeAptStartAppletAddr = 0x12ea08;
}
```

**Comment by Flat** [comment]
In addition to needing to add this version, it seems on linux the makerom-linux segmentation faults. I'm not sure who's fork is used for this build. And the most up-to-date version of makerom will not build because the rsf files are out of date/ doesn't support the ExeFs key.

**Comment by 44670** [comment]
thanks, will be fixed later

**Comment by 44670** [comment]
fixed, please try the latest build

**Comment by Flat** [comment]
Looks like it's working on this firmware in the latest commit.

**Comment by behdad1999** [comment]
so does ntr work with the fw 10.4 now?

**Comment by behdad1999** [comment]
i mean in the emunand mode

**Comment by Shadowtrance** [comment]
Yes. Assuming you're running 10.2 native firm and not 10.4 native firm. (Emunand version can still be 10.4 btw)

**Comment by behdad1999** [comment]
so my emunand can be 10.4 and ntr would still work right?

**Comment by s3r1alpari4h** [comment]
Doesn't work on my 10.4 EmuNAND. Latest build too.

**Comment by Flat** [comment]
@s3r1alpari4h are you building BootNTR yourself or using the last release? The last release is from before 10.4 support was added.

**Comment by s3r1alpari4h** [comment]
Building myself leads to an error.

**Comment by Nekrose483** [comment]
i am using an Old 3DS XL
emunand: running rxtools 10.4 (RX-E 10.4.0.29U)
sysnand: Ver. 9.2.0-24U
built it from source just now. (it builds BootNTR-Mode3.cia (and some other files) then says hit a key to continue, did so, then wipes everything a builds a new thing with BootNTR.cia and some other files.)
then i copied the latest release of ntr.bin from the zip file to the sd root, as it says to.
installed BootNTR.cia ran it, says current firmware not supported. no results.txt in the SD root. uninstalled it and tried the mode3 one. still no results. same "not supported firmware" message saying to email you.

am i doing something wrong? looking in the wrong place for results.txt english is not my first language and there is litterally no documentation. i found the link to devpro tools in an obscure folder in a makefile.md text file and installed it which let me compile without any errors on windows 10. and the only reason i knew to put ntr.bin on the SD root was through some post on reddit someone made saying you need that there. then this post that says 10.4U is supported while the change list only says 10.4J is supported.

so, i appologise for making a long post, but here's hoping for answers and hopefully help others as well.
