### ISSUE TITLE
Included makerom-linux Segmentation Fault

### ISSUE THREAD

**Issue by Flat** [44670/BootNTR#33]
The included version of makerom for linux segmentation faults when building BootNTR.

```
Makefile:180: recipe for target '/home/flat/dev/BootNTR/output/BootNTR-Mode3.cia' failed
make[1]: *** [/home/flat/dev/BootNTR/output/BootNTR-Mode3.cia] Segmentation fault (core dumped)
Makefile:143: recipe for target 'build' failed
make: *** [build] Error 2

```

**Comment by 44670** [comment]
try the latest one from ctrcommon:
https://github.com/Steveice10/ctrcommon/tree/master/tools

we will fix it later.

**Comment by Flat** [comment]
Using the latest from that link gives the following errors:

```
[RSF ERROR] Unrecognised Key: 'ExeFs'
[RSF ERROR] Error Proccessing RSF file

```

**Comment by 44670** [comment]
have you tried the latest devkitpro?

**Comment by Flat** [comment]
Yes. I have the latest devkitpro.

**Comment by 44670** [comment]
have you read the build-mode0.bat?
you should copy template-cia-0.rsf to template-cia.rsf, and do the same with resources/appinfo

**Comment by Flat** [comment]
Looks like that fixed it! I didn't even think to look at the bat files and assumed the makefile would take care of it and those were windows only. Sorry about that.
