### ISSUE TITLE
 10.4.0-29 Emunand Problem

### ISSUE THREAD

**Issue by jmapjp** [44670/BootNTR#38]
kversion:  02320100
sysnand : 4.2.0-9U
Emunand: 10.4.0-29U
[result.txt]

strHidUser: 003250ff
refHidUser: 0030b7ac
hidObj: 0035fda0
{'gxFlushDCahce': '0x12ded0', 'fsOpenFile': '0x163898', 'mountArchive': '0x12c064', 'userFsTryOpen': '0x22bc08', 'nnInitCardUpd': '0x118d78', 'regArchive': '0x228184', 'fsOpenArchive': '0x21ec5c', 'fsWriteFile': '0x163974', 'mountRom': '0x10ed84', 'hidObj': '0x35fda0', 'fsReadFile': '0x12c19c', 'getServiceHandle': '0x235818', 'aptStartApplet': '0x12ea08', 'fsUserHandle': '0x32dfa4'}
if (t == 0xe1a00006 ) {
ntrConfig->HomeMenuVersion = SYSTEM_VERSION(10.4.0-29U Emunand);
ntrConfig->HomeMenuInjectAddr = 0x12ded0;
ntrConfig->HomeFSReadAddr = 0x12c19c;
ntrConfig->HomeCardUpdateInitAddr = 0x118d78;
ntrConfig->HomeFSUHandleAddr = 0x32dfa4;
ntrConfig->HomeAptStartAppletAddr = 0x12ea08;
}

**Comment by Flat** [comment]
Please see this comment https://github.com/44670/BootNTR/issues/51#issuecomment-198556821
