### ISSUE TITLE
ntr cia launcher doesn't work after leave friend list

### ISSUE THREAD

**Issue by gilplay3000** [44670/BootNTR#4]
as I mentioned in the title, also open ntr cfw early and go on your friends list and then leave the ntr cfw simply no longer displays the menu and try to open again gives the same error.

error details:
open process failed: d9001818
current firmware not supported.
kversion: 02320100
bootntr failed

it works normal if I did not go on the friends list, but if I open the friends list ntr launcher only works if I leave the emunand and open emunand again. tested with rxtools 3.02be emunand 9.9.0-26u, sysnand 4.2.0-9u :)

**Comment by 44670** [comment]
It seems home menu was restarted for ensuring enough memory to run friend list, at this moment this issue may not be solved.
