### ISSUE TITLE
[Improvement] cheat plugins

### ISSUE THREAD

**Issue by sickness0666** [44670/BootNTR#42]
this is an improvement idea, for the cheats, i think it would be alot better if they were separated from normal plugins (no need to compile)

similar to cwcheat etc for psp, where you can have a database file that specifies cheats, have the format similar to:

_S 000400000011C500  <-- Title ID or _S CTR-ECLE  <-- Serial
_G Pokemon Alpha Sapphire  <-- Game title
_C0 Max Money, Game v1.4 <-- cheat menu code title
_L 0x08C71DC0 0x0098967F  <-- cheat code  
_C0 Have 999,999 Bp    <-- multi value cheat code
_L 0xDC000000 0x00000000
_L 0x08C71DE8 0x000F423F
_L 0xD0000000 0x00000000   

maybe also have an option like:
_B BUTTON_X or for cheats you want to toggle with a button or

_B BUTTON_R 
_B2 BUTTON_X  for having to press multiple buttons to toggle cheat on or off

having it like this, and then having just one database file or similar would meant you only need 1 file, no creating folder, and compiling, or downloading a cheat.plg, and would make it easier for people to create their own cheats for games

another way to separate it and make it easier for people, is having a built in memory searcher, instead of just having the ability to dump the ram, so that you can search it in live time instead of having to make multiple dumps

i dont know if these would be able to be done, but i think it could make it alot easier for everyone to find the values that they are looking for and making their own cheats etc

**Comment by 44670** [comment]
sorry, there are no plans for supporting cheating directly.
