### ISSUE TITLE
10.6U emuNAND

### ISSUE THREAD

**Issue by zx96** [44670/BootNTR#47]
o3DS
sysNAND: 9.2.0-20U
emuNAND: 10.6.0-31U AuReiNAND via arm9loaderhax
kversion: 02320b00

Contents of [result.txt](https://github.com/44670/BootNTR/files/170283/result.txt):
strHidUser: 003250ff
refHidUser: 0030b7ac
hidObj: 0035fda0
{'gxFlushDCahce': '0x12ded0', 'fsOpenFile': '0x163898', 'mountArchive': '0x12c064', 'userFsTryOpen': '0x22bc08', 'nnInitCardUpd': '0x118d78', 'regArchive': '0x228184', 'fsOpenArchive': '0x21ec5c', 'fsWriteFile': '0x163974', 'mountRom': '0x10ed84', 'hidObj': '0x35fda0', 'fsReadFile': '0x12c19c', 'getServiceHandle': '0x235818', 'aptStartApplet': '0x12ea08', 'fsUserHandle': '0x32dfa4'}
if (t == 0xe1a00006 ) {
ntrConfig->HomeMenuVersion = SYSTEM_VERSION(INSERT_YOUR_VERSION_HERE);
ntrConfig->HomeMenuInjectAddr = 0x12ded0;
ntrConfig->HomeFSReadAddr = 0x12c19c;
ntrConfig->HomeCardUpdateInitAddr = 0x118d78;
ntrConfig->HomeFSUHandleAddr = 0x32dfa4;
ntrConfig->HomeAptStartAppletAddr = 0x12ea08;
}

**Comment by Flat** [comment]
Please see this comment https://github.com/44670/BootNTR/issues/51#issuecomment-198556821

**Comment by 44670** [comment]
please try the latest build with 10.2 NATIVE_FIRM.
