### ISSUE TITLE
Optional dump on fail.

### ISSUE THREAD

**Issue by RePod** [44670/BootNTR#5]
With the current version I have (which I assume is the latest) when it does work, that's great. It works.

However in the few instances I try to launch it, it fails and proceeds to dump everything it needs.

Clearly it's supported (by successfully booting before and eventually booting again) and I'm also assuming you really have no use for dumps like these.

A small quality of life change would save time, headache, and confusion:
 - Prompt users to dump instead of dumping automatically.
  - Probably hint "if it's worked before don't dump".

If I'm wrong about anything let me know. Thanks!

**Comment by 44670** [comment]
Thanks for reporting, by the way, how often did you met this issue?

**Comment by RePod** [comment]
Not very often, in my case, as I typically boot it the first time and leave it (and the 3DS) running so I wouldn't need to run it again (until restart).
