### ISSUE TITLE
10.7 Issue

### ISSUE THREAD

**Issue by Dingzhu** [44670/BootNTR#54]
Hi, I've attached a result.txt from running bootNTR on my O3DS (Which seems to be 2.4 according to the text, which is strange considering I've only downloaded the latest builds). I was hoping you could figure out what's preventing me from running it.

Sysnand: 9.2.0-20U
Emunand: 10.7.0-32U
kversion: 02320b00

strHidUser: 003250ff
refHidUser: 0030b7ac
hidObj: 0035fda0
{'gxFlushDCahce': '0x12ded0', 'fsOpenFile': '0x163898', 'mountArchive': '0x12c064', 'userFsTryOpen': '0x22bc08', 'nnInitCardUpd': '0x118d78', 'regArchive': '0x228184', 'fsOpenArchive': '0x21ec5c', 'fsWriteFile': '0x163974', 'mountRom': '0x10ed84', 'hidObj': '0x35fda0', 'fsReadFile': '0x12c19c', 'getServiceHandle': '0x235818', 'aptStartApplet': '0x12ea08', 'fsUserHandle': '0x32dfa4'}
if (t == 0xe1a00006 ) {
ntrConfig->HomeMenuVersion = SYSTEM_VERSION(INSERT_YOUR_VERSION_HERE);
ntrConfig->HomeMenuInjectAddr = 0x12ded0;
ntrConfig->HomeFSReadAddr = 0x12c19c;
ntrConfig->HomeCardUpdateInitAddr = 0x118d78;
ntrConfig->HomeFSUHandleAddr = 0x32dfa4;
ntrConfig->HomeAptStartAppletAddr = 0x12ea08;
}

There was another issue submitted that had an identical result.txt, sans the kversion, but using the solution posted there didn't help. Sorry if I've done something wrong here, I'm very new to the 3DS hacking scene.

Some potentially helpful messages I caught were 
- Unknown FIRM, access-checks could not be patched
- param is missing: ntrConfig->PMSvcRunaddr
- Current firmware not supported
- bnBootNTR failed

**Comment by Dingzhu** [comment]
It seems that the bootNTR lists my firm version as 00000000. I'm still stumped as to why it's doing this...

**Comment by shendskate** [comment]
i have the same problem, running the same Sysnand + Emunand as you..but different kernel
my kversion : 02320100
we share the same problem dude..hope someone will come wih some good answer

**Comment by 44670** [comment]
please try the latest build with 10.2 NATIVE_FIRM.
