### ISSUE TITLE
Unknown firm

### ISSUE THREAD

**Issue by YunSun-CN** [44670/BootNTR#55]
A9LH SysNand: 10.7.0-32J

strHidUser: 003260df
refHidUser: 0030c794
hidObj: 00360da0
{'gxFlushDCahce': '0x12ded0', 'fsOpenFile': '0x163898', 'mountArchive': '0x12c064', 'userFsTryOpen': '0x22bdbc', 'nnInitCardUpd': '0x118d78', 'regArchive': '0x228338', 'fsOpenArchive': '0x21ee10', 'fsWriteFile': '0x163974', 'mountRom': '0x10ed84', 'hidObj': '0x360da0', 'fsReadFile': '0x12c19c', 'getServiceHandle': '0x2359cc', 'aptStartApplet': '0x12ea08', 'fsUserHandle': '0x32efa4'}
if (t == 0xea00001f ) {
ntrConfig->HomeMenuVersion = SYSTEM_VERSION(INSERT_YOUR_VERSION_HERE);
ntrConfig->HomeMenuInjectAddr = 0x12ded0;
ntrConfig->HomeFSReadAddr = 0x12c19c;
ntrConfig->HomeCardUpdateInitAddr = 0x118d78;
ntrConfig->HomeFSUHandleAddr = 0x32efa4;
ntrConfig->HomeAptStartAppletAddr = 0x12ea08;
}

**Comment by Shadow322** [comment]
Um yea NTR does not support NATIVE_FIRM 10.4

**Comment by 44670** [comment]
use the 10.2 native_firm and try again
