### ISSUE TITLE
I seem to be having issues with streaming. Windows 10

### ISSUE THREAD

**Issue by MistieKitteh** [44670/BootNTR#59]
This is the console output 
NTR debugger by cell9
> import sys;sys.path.append('.\python\Lib')
null
> for n in [n for n in dir(nc) if not n.startswith('_')]: globals()[n] = getattr(nc,n)    
null
Commands available: 
> repr([n for n in dir(nc) if not n.startswith('_')])
['attachprocess', 'bpadd', 'bpdis', 'bpena', 'connect', 'data', 'disconnect', 'listprocess', 'listthread', 'memlayout', 'queryhandle', 'reload', 'remoteplay', 'resume', 'sayhello', 'sendfile', 'write']
> connect('192.168.1.52', 8000)
null
Server connected.
> remoteplay()
null
Will be disconnected in 10 seconds to enhance performance.
cpu was locked on 804MHz, L2 Enabled
starting remoteplay...
buf: 07001000, size: 00022000
remotePC: 001231d0
> disconnect()
null
Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall.
Server disconnected.

No idea what it means but streaming doesn't work.

**Comment by teconmoon** [comment]
This is normal output. Are you running the NTRDebugger and NTRViewer.exe simultaneously?

**Comment by 44670** [comment]
Seems the remote play has been activated successfully. Try the firewall settings.

**Comment by xErwin** [comment]
You need to disable antivirus (firewall + protection)
