### ISSUE TITLE
Some game don't stream properly unless their online features are activated....

### ISSUE THREAD

**Issue by ApacheThunder** [44670/BootNTR#60]
Many of the games that I've tried don't appear to stream properly. Noteably the Pokemon games which was real buzzkill.

However I managed to discover the cause.

Turns out for some reason the game has to be connected to the internet. As soon as I connect to the internet via the PSS, video stream for the game returns and operates correctly in NTRViewer.

This may partly be why a few other games aren't working with this properly. I have noticed also that Ocarina of Time 3D does not stream properly either but that game has no online features at all, so there's no workaround for that game. Mario kart 7 appears to get along fine with NTRViewer and single player modes work with it just fine.

Hopefully game compatibility can be resolved as it's kinda of spotty right now. :(

Despite my crappy DSL wifi router, the performance is better then expected. Get around 80%-95% on average. It does get choppy at times, but in it's current state it beats recording a game from my makeshift camera box, so it's definitely a step in the right direction!

**Comment by 44670** [comment]
The manual was updated for this situation.
