### ISSUE TITLE
NTR debugger, remoteplay() name 'remoteplay' is not defined

### ISSUE THREAD

**Issue by GameShogun** [44670/BootNTR#63]
when i input the comand remoteplay() on the NTR debugger , i get this error

> remoteplay()
name 'remoteplay' is not defined
   en IronPython.Runtime.Operations.PythonOps.GetVariable(CodeContext context, String name, Boolean isGlobal, Boolean lightThrow)
   en IronPython.Compiler.LookupGlobalInstruction.Run(InterpretedFrame frame)
   en Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   en Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   en IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
   en IronPython.Compiler.PythonScriptCode.Run(Scope scope)
   en IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   en IronPython.Compiler.RuntimeScriptCode.Run(Scope scope)
   en Microsoft.Scripting.SourceUnit.Execute(Scope scope, ErrorSink errorSink)
   en Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
   en ntrclient.CmdWindow.runCmd(String cmd)

Please help me! and Thanks

**Comment by urherenow** [comment]
Are you using ALL of the new files and not just replacing ntr.bin on the 3ds? You should use the client and viewer executables as well, and have them both running.

**Comment by urherenow** [comment]
Wait... This is the wrong repo for this wuestion anyway, all this does is give you an easy way to launch NTR. You need to actually update your NTR from its repo.

**Comment by GameShogun** [comment]
Ok thanks!! i try, and later coment if it works or not :)

**Comment by GameShogun** [comment]
i do with this repo and the problem is the same , remoteplay()
name 'remoteplay' is not defined

**Comment by urherenow** [comment]
You are in bootNTR. This repo has nothing to do with  the functionality of ntr and will not fix your problem.
