### ISSUE TITLE
NTR not streaming correctly

### ISSUE THREAD

**Issue by Shinigati** [44670/BootNTR#66]
So this is a weird issue, apparently NTR streaming doesn't work properly with my router, instead i will simply only get the top screen of my 3ds streaming into NTR viewer but if i setup my computers wifi card to act as an AP of it's own it works fine. and yes i have already added firewall rules to both my computer and router so i'm not sure what the problem could be.

**Comment by Shinigati** [comment]
I should also note that when i connect to the 3ds i get the following error:
> connect('192.168.0.10', 8000)
null
Server connected.
rtRecvSocket failed: 00000000patching smdh

**Comment by urherenow** [comment]
Maybe a QOS or other such priority issue, if you're sure all correct ports are open.

**Comment by Shinigati** [comment]
I disabled QoS so i really don't know what's going on but having my computer host a SSID causes issues on my machine so i'd rather try and get it working properly with my router.

**Comment by imthe666st** [comment]
> `connect('192.168.0.10', 8000)
> null
> Server connected.
> rtRecvSocket failed: 00000000patching smdh`

This 'error' is normal

**Comment by 44670** [comment]
Check the firewall settings and try again, please read the manual carefully before starting streaming.
