### ISSUE TITLE
going from preview to preview 2, none will load now

### ISSUE THREAD

**Issue by kurrptsenate** [44670/BootNTR#68]
preview 1 was working.  i wanted to upgrade to preview 2.  i deleted the installed cia with system settings, then copied the bin file and new cia to the SD card.  I installed new cia with FBI.  when i try to run the installed CIA i get an error saying it can't determine which FW im on (10.7 from guide) and won't work any longer

**Comment by Shadow322** [comment]
All u need to do is replace the ntr.bin the cia is the same

**Comment by kurrptsenate** [comment]
i replaced both as I wasn't aware.  I deleted the first installed CIA (with system settings) and replaced the bin file.  No version will load for me now

**Comment by kurrptsenate** [comment]
I installed with FBI every time as well

**Comment by kurrptsenate** [comment]
when i open the BootNTR it goes through these lists of dumps after saying access checks couldn't be done

**Comment by kurrptsenate** [comment]
I tried installing the preview 1 CIA with both versions of the bin.  It's
broken for me for some reason saying it can't determine the FW

i tried updating with system settings.  says i can't as i'm on 10.7 32U

**Comment by kurrptsenate** [comment]
says there's a parameter missing (first error that pops up when trying to
run BootNTR)

ntrconfig->PMSvcRUNADDr

not sure if that's any help

**Comment by donneeee** [comment]
hmm. updaing AuReiNAND to the lastest version broke my BootNTR.cia (preview 2)

"current firmware not supported". any fix coming soon?

**Comment by Shadow322** [comment]
Use NTR firmware.bin from the NTR folder for your console type

**Comment by kurrptsenate** [comment]
I never touched that file when preview 1 was working.  I can try replacing
it to see if that makes a difference

**Comment by kurrptsenate** [comment]
Replacing that file had no effect

**Comment by donneeee** [comment]
so all files were overwritten correctly then?

BootNTR.cia -----> root

ntr.bin -------> root

(i'm assuming your using aureinand so...) the firmware from this page: https://github.com/AuroraWright/AuReiNand/wiki/Installation-and-Upgrade
firmware.bin ------> root\aurei\

**Comment by kurrptsenate** [comment]
That is correct.  Not sure what else to try at this point

**Comment by donneeee** [comment]
the only thing i can suggest is to update your CFW if you already hadn't. not sure why NRT bricked on you. you are running aureinand right?

**Comment by kurrptsenate** [comment]
Yes.  Version 5.0.  How would I go about that?

**Comment by donneeee** [comment]
https://github.com/AuroraWright/AuReiNand/wiki/Installation-and-Upgrade explains it all. 

since you already have the firmware.bin file that is suppose to make NTR work, you dont need to redo that. i did however delete everything in my aurei folder except payloads and the firmware.bin to ensure i didn't mess anything up

also you don't need to copy patchchanger and menuhax over to your sd card if you don't already use them

**Comment by kurrptsenate** [comment]
I followed the main guide from 9.2, to red downgrade, to otp, to cfw.  I'll
try what you suggested right now and let you know.

Thanks

**Comment by nobitagamer** [comment]
I think this is not problem since AuReiNand 5.0+ has option to use sysNAND firmware so you should delete the patched_* file from /aurei folder and override this [NTR firmware](http://www70.zippyshare.com/v/Fbj6n1vB/file.html) from https://github.com/AuroraWright/AuReiNand/wiki/Installation-and-Upgrade and try again. Hope it will run (I have updated sysNAND 10.7.0-32U and working NTR CFW Preview 2 + AuReiNand 5.1.1)

**Comment by kurrptsenate** [comment]
what file are you talking about that's specifically patched?  one of the
firmwares that were renamed?

**Comment by kurrptsenate** [comment]
should i start from this section of the guide?


Section IV - Copying RedNAND data to SysNAND

   1. Reboot, then open Decrypt9 from arm9loaderhax by holding Start on boot
   2. Go to "SysNAND Options"
   3. Go to "SysNAND Backup/Restore..."
   4. Select "NAND Restore *(keep a9lh)*"
   5. Confirm and restore from emuNAND_original.bin

**Comment by nobitagamer** [comment]
No, the patched_* firmwares are cached version from AuReiNand for fast boot, you delete them to re-create the new patched of NTR firmware version. The guide above just to download the NTR firmware (actually is 10.2, your updated sysNAND firmware is 10.4 that cannot run NTR)

**Comment by kurrptsenate** [comment]
which files am I deleting so it creates new ones?

**Comment by kurrptsenate** [comment]
i removed all the firmwares from the payload folder and rebooted.  that had
no effect

**Comment by kurrptsenate** [comment]
it continues to show firmware as 000000000 and will not run

**Comment by nobitagamer** [comment]
You need the following file: aurei/firmware.bin (this is NTR firmware download above), don't put any firmware in payload folder.

**Comment by nobitagamer** [comment]
Delete the aurei/patched_* files.

**Comment by kurrptsenate** [comment]
i tried it with none of the files besides the config files.  same result :(

**Comment by nobitagamer** [comment]
can you list your /aurei folder content?

**Comment by kurrptsenate** [comment]
right now
[payloads]
config.bin
firmware.bin

payloads is empty

**Comment by nobitagamer** [comment]
Ok, delete the config.bin to force display config screen and check the following options:
(x ) Autoboot SysNAND
(x ) Use SysNAND FIRM as default (A9LH-only)
(x ) Force A9LH detection
( ) Use second EmuNAND as default
(x ) Enable region/language emulation
( ) Use developer UNITINFO
(x ) Show current NAND in System Settings
(x ) Show GBA boot screen in patched AGB_FIRM
(x ) Enable splash screen with no screen-init

Make sure firmware.bin is this file http://www70.zippyshare.com/v/Fbj6n1vB/file.html

**Comment by kurrptsenate** [comment]
that worked!!!

i had the right firmware in there (didn't bother redownloading it).  seems
like the act of deleting the config file forced it to remake those files.
thanks a lot!

**Comment by 44670** [comment]
wow :/
