### ISSUE TITLE
10.7.0U A9LH - Firmware not supported

### ISSUE THREAD

**Issue by BtheDestroyer** [44670/BootNTR#69]
Not sure what firmwares ARE supported as it's not listed anywhere online, so if I could at least be told that it'd be helpful. Some people say you need to be on 4.5, some people say 9.2, some people say all versions work, and it's all just pretty inconsistent. 

EDIT: Also, I'm using ARN and the kversion at the end of the log is 02320b00

**Comment by nobitagamer** [comment]
You need NTR firmware (10.2) from https://github.com/AuroraWright/AuReiNand/wiki/Installation-and-Upgrade. If you don't put firmware.bin into /aurei folder, it will use the FIRM from sysNAND (that's 10.4 don't support by NTR).

**Comment by BtheDestroyer** [comment]
Just tried replacing my firmware.bin with that one and still get the same error.

**Comment by nobitagamer** [comment]
You can try solution i posted in this https://github.com/44670/BootNTR/issues/68#

**Comment by urherenow** [comment]
You can't simply drop a new file in and expect it to work. You need to delete any prepatched stuff AUReiNand made, and the config file, so it can make bew ones.

**Comment by BtheDestroyer** [comment]
@nobitagamer @urherenow this caused it to work! Thanks for the troubleshooting, newb with cfw and stuff like this.
