### ISSUE TITLE
AuReiNAND A9LH - If NTR Isn't working with a firmware.bin  

### ISSUE THREAD

**Issue by Kikoshi** [44670/BootNTR#71]
Hello, 
I just wanted to mention something that wasn't very specific with the new update of ARN:

(x ) Autoboot SysNAND
(x ) Use SysNAND FIRM as default (A9LH-only) * This needs to be enabled so that it reads the Firmware.bin file in aurei folder*
(x ) Force A9LH detection
( ) Use second EmuNAND as default
(x ) Enable region/language emulation
( ) Use developer UNITINFO
(x ) Show current NAND in System Settings
(x ) Show GBA boot screen in patched AGB_FIRM
( ) Enable splash screen with no screen-init

**Comment by 44670** [comment]
Issue Tracker is not a forum, please stop flooding with useless information.
