### ISSUE TITLE
Switching games

### ISSUE THREAD

**Issue by TheMrDew** [44670/BootNTR#72]
Is there a command to turn off remoteplay.  I know that switching games while using remoteplay causes the load screen to stay on forever.  If there is a command to disconnect from NTRViewer, please share it and if there isn't one, would it be possible to add one to a future update so we wouldn't have to reboot or restart our 3ds' and restart the debugger and viewer every time we switch games

**Comment by TheMrDew** [comment]
One last thing I forgot to mention.  After the debugger disconnects  to enhance performance, if I where to input the connect command with my ip address, the debugger starts not responding and I have to exit it.  If this could be answered as well

**Comment by 44670** [comment]
There was no command to stop remotplay. You could simply reboot your console to do that.
