### ISSUE TITLE
NDS mode not working

### ISSUE THREAD

**Issue by TheMrDew** [44670/BootNTR#73]
I have a copy of Ace Attorney Apollo Justice for the NDS and I wanted to see how BootNTR would work while streaming this game.  When I went to play it, I noticed that NTR menu wouldn't open.  Is this feature solely for 3ds?  If so, that really stinks for those wanting to use this for DS games

**Comment by astronautlevel2** [comment]
Launching DS games reboots the 3ds into reboot mode, and as such NTR is unloaded.

**Comment by 44670** [comment]
It is not possible at this moment.
