### ISSUE TITLE
Crashing with Firmware 11.0.0

### ISSUE THREAD

**Issue by Dragonas** [44670/BootNTR#89]
I updated my N3DS to latest firmware 11.0.0 yesterday and NTR is not working anymore since then. Is it the known issue and we are developing the newer version of NTR for FW 11.0.0?
Best regard!

**Comment by Margen67** [comment]
You need to use a 10.2 firmware.bin.  https://github.com/44670/BootNTR/issues/36

**Comment by Dragonas** [comment]
Can you please give me the download link? Sorry, I'm a newbie

**Comment by 44670** [comment]
This issue is closed for requesting files.
