### ISSUE TITLE
result.txt: 8.1.0-9U (Zelda O3DS XL)

### ISSUE THREAD

**Issue by CrispyYoshi** [44670/BootNTR#9]
kversion: 02320100
SysNAND: 8.1.0-9U (I did this on SysNAND via the NTR .cia, but my EmuNAND is GW3D 9.9.0-26U)

strHidUser: 0023226c
refHidUser: 00220a38
hidObj: 002767b8
{'gxFlushDCahce': '0x13f2d8', 'fsOpenFile': '0x1549e0', 'mountArchive': '0x10df08', 'userFsTryOpen': '0x19df38', 'nnInitCardUpd': '0x13719c', 'regArchive': '0x1a2984', 'fsOpenArchive': '0x19b570', 'fsWriteFile': '0x154abc', 'mountRom': '0x10e254', 'hidObj': '0x2767b8', 'fsReadFile': '0x11a994', 'getServiceHandle': '0x1aa0bc', 'aptStartApplet': '0x12aac0', 'fsUserHandle': '0x238df4'}
if (t == 0xe28f3fde ) {
ntrConfig->HomeMenuVersion = SYSTEM_VERSION(INSERT_YOUR_VERSION_HERE);
ntrConfig->HomeMenuInjectAddr = 0x13f2d8;
ntrConfig->HomeFSReadAddr = 0x11a994;
ntrConfig->HomeCardUpdateInitAddr = 0x13719c;
ntrConfig->HomeFSUHandleAddr = 0x238df4;
ntrConfig->HomeAptStartAppletAddr = 0x12aac0;
}

**Comment by 44670** [comment]
fixed, thanks for reporting
